# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: UNSW Securtiy Society
email: &#x65;&#x78;&#x65;&#x63;&#x73;&#x40;&#x75;&#x6E;&#x73;&#x77;&#x73;&#x65;&#x63;&#x75;&#x72;&#x69;&#x74;&#x79;&#x2E;&#x63;&#x6F;&#x6D;
twitter_username: jekyllrb
github_username:  unswsecuritysociety

# Template Keys
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.unswsecurity.com" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
